---
title: "Movie  Data - RNN/LSTM - NETFLIX "
output: html_notebook
---

# Movie Sentiment Analysis using RNN/LSTM

WE will use NETFLIX move review data for predicting sentiments based on the movie reviews .

We will predict either a positive(1) or a negative(0) sentiment for a given movie review 

```{r}
library(keras)
max_features <- 20000
batch_size <- 32

# Cut texts after this number of words (among top max_features most common words)
maxlen <- 80  

x_train <- nflix$train$x
y_train <- nflix$train$y
x_test <- nflix$test$x
y_test <- nflix$test$y

```

# Looking at the training data - features 
```{r}
head(x_train,1)
```
# looking at the sentiment labels - training 
```{r}
head(y_train,1)
```

# Data exploration 

```{r}
cat(length(x_train), 'train sequences\n')
cat(length(x_test), 'test sequences\n')

cat('Pad sequences (samples x time)\n')
x_train <- pad_sequences(x_train, maxlen = maxlen)
x_test <- pad_sequences(x_test, maxlen = maxlen)
cat('x_train shape:', dim(x_train), '\n')
cat('x_test shape:', dim(x_test), '\n')

```

# Building the model with Keras 

```{r}
cat('Build model...\n')
model2_keras <- keras_model_sequential()
model2_keras %>%
  layer_embedding(input_dim = max_features, output_dim = 128) %>% 
  layer_lstm(units = 64, dropout = 0.2, recurrent_dropout = 0.2) %>% 
  layer_dense(units = 1, activation = 'sigmoid')

# Try using different optimizers and different optimizer configs
model2_keras %>% compile(
  loss = 'binary_crossentropy',
  optimizer = 'adam',
  metrics = c('accuracy')
)

fit_keras <- fit(
    object           = model2_keras, 
    x                = x_train, 
    y                = y_train,
    batch_size       = batch_size, 
    epochs           = 1,
    validation_data = list(x_test, y_test)
    )


```
```{r}
# Print the final model
fit_keras
```
```{r}
# Plot the training/validation history of our Keras model
library(lime)
library(tidyquant)
library(rsample)
library(recipes)
library(yardstick)

plot(fit_keras) +
    theme_tq() +
    scale_color_tq() +
    scale_fill_tq() +
    labs(title = "Neural Net Training Results")
```
```{r}
# Predicted Class
yhat_keras_class_vec <- predict_classes(object = model2_keras, x = as.matrix(x_test)) %>%
    as.vector()

# Predicted Class Probability
yhat_keras_prob_vec  <- predict_proba(object = model2_keras, x = as.matrix(x_test)) %>%
    as.vector()
```

```{r}
# Format test data and predictions for yardstick metrics
estimates_keras_tbl <- tibble(
    truth      = as.factor(y_test) %>% fct_recode(yes = "1", no = "0"),
    estimate   = as.factor(yhat_keras_class_vec) %>% fct_recode(yes = "1", no = "0"),
    class_prob = yhat_keras_prob_vec
)

estimates_keras_tbl
```

```{r}
options(yardstick.event_first = FALSE)
# Confusion Table
estimates_keras_tbl %>% conf_mat(truth, estimate)
# Accuracy
estimates_keras_tbl %>% metrics(truth, estimate)
# AUC
estimates_keras_tbl %>% roc_auc(truth, class_prob)
# Precision and Recall
tibble(
    precision = estimates_keras_tbl %>% precision(truth, estimate),
    recall    = estimates_keras_tbl %>% recall(truth, estimate)
)
```




